<?xml version="1.0" encoding="utf-8"?><Database Name="testdb" Class="LinqToSqlTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\testdb.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DbTest.Properties.Settings" SettingsPropertyName="testdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.members" Member="members">
    <Type Name="members">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>